kind: pipeline
name: default

steps:

- name: build
  image: pfeifenjoy/argparse
  commands:
  - cmake -DCMAKE_BUILD_TYPE=Debug -H. -Bbuild
  - cmake --build build

- name: test
  image: pfeifenjoy/argparse
  commands:
  - ctest --verbose build

- name: memcheck
  image: pfeifenjoy/argparse
  commands:
  - valgrind --leak-check=yes --error-exitcode=1 --suppressions=./.valgrind-suppressions ./build/test/argparse_tests
  - valgrind --leak-check=yes --error-exitcode=1 ./build/test/argparse_set_tests
  - valgrind --leak-check=yes --error-exitcode=1 ./build/test/argparse_options_tests

- name: linux
  image: pfeifenjoy/argparse
  commands:
  - rm -rf build
  - cmake -DCMAKE_BUILD_TYPE=Release -H. -Bbuild
  - cmake --build build --target package


- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
        from_secret: gitea_token
    base_url: https://gitea.metthub.de
    files: build/argparse-*
  checksum:
    - md5
    - sha1
    - sha256
    - sha512
    - adler32
    - crc32
  when:
    event: tag
