kind: pipeline
name: default

steps:

- name: build
  image: pfeifenjoy/argparse
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cd ..

- name: test
  image: pfeifenjoy/argparse
  commands:
  - cd build
  - ctest --verbose .
  - cd ..

- name: memcheck
  image: pfeifenjoy/argparse
  commands:
  - valgrind --leak-check=yes --error-exitcode=1 --suppressions=./.valgrind-suppressions ./build/argparse_tests
